# -*- coding: utf-8 -*-
"""SAIPO MOD 2abr26 _ public.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r91CAl_9Xhj_YLeoz9RDs1ZrH6W64CsJ
"""

# -*- coding: utf-8 -*-
"""
Created on Wed Mar 11 16:38:27 2026

@author: pepep
"""

############ Libraries #######################
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like
#from pandas_datareader import data as pdr
import yfinance as yf
import random
import math
from timeit import default_timer

############ Dataframe construction ###############
#yf.pdr_override()
df = pd.read_csv('/your_datafile.csv', header=0, index_col=0)

period = 52 #*252 dairy, *52 weekly *12 monthly
assets = df.columns

df.index = pd.to_datetime(df.index, dayfirst=True) #yearfirst= False
df = df.interpolate(limit_direction='both', method='polynomial', order=3)
df = df.dropna(how='any')

df = df.dropna(axis=1, how='all')


df.isna() # na values
na = df.isna().sum()
na = pd.DataFrame(na)

# Calculate daily returns
#df_returns = df.pct_change()
df_returns = df.pct_change(periods=1).dropna()

rf = 0.06   # risk-free rate anual
#rf= ((1+rf)**(1/period)-1) #convert rf in same time-unit
marr = 0.00/period # minimum aceptable rate of return anual


# Expected value anual
def Ves(assets, returns):
    ves = []
    for serie in assets:
        x,rangos = np.histogram(returns[serie],bins=10)
        y=[]
        for i in range(len(rangos)-1):  #rangos (arreglo de tamaño 11)
            y.append((rangos[i+1]+rangos[i])/2) #marca clase
        p = x/len(df_returns) # Frecuencia relativa
        ve = sum(p*y) #*252 SI ES DIARIO, *52 SEMANAL *12 MENSUAL
        ves.append(ve)
    return ves

ves = Ves(assets, df_returns)
ves= np.array(ves)
ves = ((1+ves)**period)-1 #anualizando
ves_data=pd.DataFrame(ves, index=assets, columns=['VE'])

""" Expected return Constraint """
assets_drop = list(ves_data.index[(ves_data['VE'] < marr)]) # Assets < MARR
ves_final = ves_data[(ves_data['VE'] >= marr)] #Assets >= MARR
ves = np.array(ves_final['VE'])
assets = ves_final.index

# df renovated
df = df.drop(assets_drop, axis = 1)
df_returns = df_returns.drop(assets_drop, axis = 1)
ves_data = ves_final


def calculos(df_returns):
    r = np.array(df_returns.mean()) # average return
    r = ((1+r)**period)-1 # anualizando
    C = np.cov(df_returns.transpose()) # variance-covariance matrix
    desv_std = np.array(np.std(df_returns))*period**(1/2) # Standard deviation
    Corr = df_returns.corr() # Correlation
    return r, C, desv_std, Corr

r, C, desv_std, Corr = calculos(df_returns)

######################## Functions ################################
# Addition of a list
def addition(array):
    addition = 0
    for i in array:
        addition += i
    return addition

# Normalize a list
def normalize(array):
    array2 = []
    for i in array:
        i = i/addition(array)
        array2.append(i)
    return array2

# Random weights
def weights_random(n_assets):
    weights = []
    for i in range(n_assets):
        weights.append(random.randint(0,100))
    weights = normalize(weights)
    w = np.array(weights)
    return w

w = weights_random(len(assets))

def sigma(w, C): # Portfolio's variance
    return np.dot(w,np.dot(C,w.T))

def portfolio_risk(w, C):
    """
    Calcula la volatilidad del portafolio.
    Asegura que w y C tengan dimensiones compatibles para un escalar.

    Calculate the portfolio volatility.
    Ensure that w and C have dimensions compatible with a scalar
    """
    w = np.asarray(w).flatten()
    C = np.asarray(C)

    # Cálculo matricial w^T * C * w
    variance = np.dot(w, np.dot(C, w))

    # np.maximum evita problemas con números negativos infinitesimales por precisión
    return np.sqrt(np.maximum(0, variance)).item()*period**(1/2)



def Sharpe_port(return_portfolio, rf, risk_portfolio): # Sharpe with correlation
    return (return_portfolio - rf) / risk_portfolio

def Sharpe(return_portfolio, rf, sigma): # Classic Sharpe
    return (return_portfolio - rf) / (sigma**(1/2)*period**(1/2))

def return_port(ves, w):
    """Calcula el rendimiento esperado como escalar.
    Calculate the expected return as a scalar
    """
    ves = np.asarray(ves).flatten()
    w = np.asarray(w).flatten()
    return np.dot(ves, w).item()

def corr_prom(w, desv_std, p_risk):
    """
    Calcula la correlación promedio ponderada del portafolio.
    Optimizado para evitar ciclos anidados.
    Calculate the weighted average correlation of the portfolio.
    Optimized to avoid nested loops.
    """
    # Calculamos la varianza individual ponderada: sum(w_i^2 * sigma_i^2)
    weighted_var_individual = np.sum((w**2) * (desv_std**2))

    # La varianza total del portafolio es: V_indiv + V_cross
    # Por lo tanto, la parte de covarianza cruzada es:
    cross_term = (p_risk**2) - weighted_var_individual

    # Calculamos el denominador para promediar: sum_{i != j} (w_i * w_j * sigma_i * sigma_j)
    # Esto se obtiene del cuadrado de la suma de (w * sigma) menos la suma de los cuadrados
    sum_w_std = np.sum(w * desv_std)
    denominator = (sum_w_std**2) - weighted_var_individual

    # Evitar división por cero si el portafolio está concentrado en un solo activo
    if denominator == 0: return 0
    return cross_term / denominator

def RegularPerturbation(w, q):
    """
    Perturbación: transfiere peso de un activo a otro y normaliza.
    Disturbance: transfers weight from one asset to another and normalizes
    """
    w_new = w.copy()
    idx1, idx2 = random.sample(range(len(w_new)), 2)

    # Lógica de transferencia corregida
    transfer = min(q, w_new[idx1])
    w_new[idx1] -= transfer
    w_new[idx2] += transfer

    # Normalización de seguridad para mantener sum(w) == 1.0
    return w_new / np.sum(w_new)

def Equilibrium(list_sharpes):
    kmax = 5
    i = np.array(list(range(1,kmax+1)))
    E = np.array(list_sharpes[-kmax:])
    CE = sum(i*E)
    sumE = sum(E)
    m = ((12*(CE)) - (6*(kmax+1)*sumE)) / ((kmax**3)-kmax)
    return m

def Solutions(sharpe, n_assets, expect_return, risk, correlation, weights):
    # mem_sharpe = portfolio[3]
    mem_sol_sharpe = pd.DataFrame(sharpe)
    mem_sol_sharpe.columns = ['Sharpe']

    # mem_n_assets = portfolio[7]
    mem_sol_n_assets = pd.DataFrame(n_assets)
    mem_sol_n_assets.columns = ['Cantidad de activos']

    # mem_ves = portfolio[5]
    mem_sol_ves = pd.DataFrame(expect_return)
    mem_sol_ves.columns = ['Rendimiento esperado']

    # mem_risk = portfolio[6]
    mem_sol_risk = pd.DataFrame(risk)
    mem_sol_risk.columns = ['Riesgo del portafolio']

    # mem_corr = portfolio[4]
    mem_sol_corr = pd.DataFrame(correlation)
    mem_sol_corr.columns = ['Correlación promedio']

    # mem_weights = portfolio[2]
    mem_sol_weights=pd.DataFrame(weights, columns=assets)

    Sols = pd.concat([mem_sol_sharpe, mem_sol_n_assets, mem_sol_ves, mem_sol_risk, mem_sol_corr, mem_sol_weights], axis=1, sort=False )
    # Guardar los resultados en archivo csv
    # Sols.to_csv(f"C:\\Users\\Manuel\\Desktop\\Maestria en Ciencias de la Ingenieria\\Portafolios\\Solutions TAIPO-SAIPO-TA\\Sols_SAIPO_I7_NO_restriction{default_timer()}.csv",header=True,index=True)

    return Sols

######################## TA ALgorithm ################################
# Parameters

"""
T0 = 300.0 # Initial Temperature
Tf = 0.000127 # Final Temperature
alfa = 0.975 #Cooling ratio .95
T = T0 # Current Temperature
Tol = T
c = 3.51
Lmax = len(assets) * c
L0 = 1
"""
T0 =0.944879 # Initial Temperature
Tf = 0.000074 # Final Temperature
alfa = 0.93 #Cooling ratio .95
T = T0 # Current Temperature
Tol = T
c = 3.51
Lmax = len(assets) * c
L0 = 300
lncf = math.log(Tf, math.e)
lnci = math.log(T0, math.e)
lna = math.log(alfa, math.e)
n = (lncf - lnci) / lna
lnLmax = math.log(Lmax, math.e)
lnL0 = math.log(L0, math.e)
Beta = math.e **((lnLmax-lnL0)/n)
L = L0
iteration = 0

parameters = [T0, Tf, alfa, L0, Beta]

#################  TA Algorithm ##################
def SAIPO(parameters):
    T = parameters[0]
    Tf = parameters[1]
    alfa = parameters[2]
    L = parameters[3]
    Beta = parameters[4]

    """ Generate initial solution """
    w_current = weights_random(len(assets))
    risk_portfolio = portfolio_risk(w_current, C) # Usa C directamente
    return_portfolio = return_port(ves, w_current)
    Sharpe_current = Sharpe_port(return_portfolio, rf, risk_portfolio)
    Corr_prom = corr_prom(w_current, desv_std, risk_portfolio)
    #Sharpe_current = Sharpe_port(return_portfolio, rf, risk_portfolio)
    num_assets = np.count_nonzero(np.array(w_current))
    s = Sharpe_current
    Assets_best = w_current
    """ Generate initial solution """

    # Auxiliary lists
    temp_list = [T]
    mem_sharpe = [round(Sharpe_current,4)]
    mem_corr = [round(Corr_prom,6)]
    mem_weights = [w_current]
    mem_ves = [round(return_portfolio,6)]
    mem_risk = [round(risk_portfolio,6)]
    mem_n_assets = [num_assets]

    ################# Beginning of cycle #############################
    iteration = 0
    while T >= Tf:
        k = 0
        while k < L:
            w_aux1 = w_current
            #w_aux2 = np.array(w_aux1)
            ################################################################
            q = 1/(len(w)*5)
            w_new = RegularPerturbation(w_current, q)
            return_port_new = return_port(ves, w_new)
            risk_port_new = portfolio_risk(w_new, C) # Pasamos C directamente
            Sharpe_new = Sharpe_port(return_port_new, rf, risk_port_new)
            Delta = Sharpe_new - Sharpe_current
            rand = random.random()
            boltzman = math.e ** (Delta/T)
            if Delta > 0:
                Sharpe_current = Sharpe_new
                w_current = tuple(w_new)
                if Sharpe_current > s: #Best obtained value
                    s = Sharpe_current
                    Assets_best = w_current
            elif rand < boltzman:
                Sharpe_current = Sharpe_new
                w_current = tuple(w_new)
            else:
                Sharpe_current = Sharpe_current
                w_current = tuple(w_current)
            k += 1
            w_current = np.array(w_current)
            Assets_best = np.array(Assets_best)

        return_port_mem = return_port(ves,w_current)
        risk_port_mem = portfolio_risk(w_current, C)
        corr_prom_mem = corr_prom(w_current, desv_std, risk_port_mem)
        n_assets = np.count_nonzero(np.array(w_current))


        # Update parameters
        L = Beta*L
        T = T*alfa
        temp_list.append(T)
        mem_sharpe.append(round(Sharpe_current,4))
        mem_corr.append(round(corr_prom_mem,6))
        mem_weights.append(w_current)
        mem_ves.append(round(return_port_mem,6))
        mem_risk.append(round(risk_port_mem,6))
        mem_n_assets.append(n_assets)

        iteration +=1


    best_assets = []
    for i in Assets_best:
        best_assets.append(round(i,4))
    portfolio_final = pd.DataFrame(best_assets, index=assets, columns=['Weight'])
    portfolio_final = portfolio_final.sort_values(by='Weight', ascending=False)
    risk_final = sigma(Assets_best,C)
    risk_port_final = portfolio_risk(Assets_best, C)
    expected_return = return_port(ves, Assets_best)
    correlacion = corr_prom(Assets_best, desv_std, risk_port_final)
    SR = Sharpe(expected_return, rf, risk_final)
    solutions = Solutions(mem_sharpe, mem_n_assets, mem_ves, mem_risk, mem_corr, mem_weights)
    n_activos = np.count_nonzero(np.array(Assets_best))
    print(f"Best sharpe = {round(s,4)}")
    print(f"Expected Value = {round(expected_return,4)}")
    print(f"Volatility = {round(risk_port_final,6)}")
    print(f"Average Correlation = {round(correlacion,6)}")
    print(f"Number of assets = {n_activos}")

    sharpe_plot = []
    for sharpe in mem_sharpe:
        #sharpe = sharpe*-1
        sharpe_plot.append(sharpe)
    """
    # Solutions plot
    plt.figure(figsize = (10,6))
    plt.plot(list(range(len(temp_list))),sharpe_plot)
    # plt.plot(list(range(len(temp_list))),chaotic_s)
    plt.xlabel('Iteration')
    plt.ylabel('Sharpe Ratio')
    plt.title('SA optimization')
    plt.show('SA Optimization Process ')
    """

    # Solutions plot
    plt.figure(figsize = (10,6))
    plt.plot(list(range(len(temp_list))), sharpe_plot)

    # Aumentamos el tamaño de las etiquetas de los ejes
    plt.xlabel('Iteration', fontsize = 14)
    plt.ylabel('Sharpe Ratio', fontsize = 14)

    # Aumentamos el tamaño del título y los números de los ejes (ticks)
    plt.title('SA Optimization Process', fontsize = 16, fontweight = 'bold')
    plt.xticks(fontsize = 12)
    plt.yticks(fontsize = 12)

    plt.grid(True, linestyle='--', alpha=0.6) # Recomendado para papers para facilitar la lectura
    plt.show()


    solutions = Solutions(mem_sharpe, mem_n_assets, mem_ves, mem_risk, mem_corr, mem_weights)
    # print(solutions)
    return s, expected_return, risk_port_final, correlacion, n_activos, Assets_best, solutions, risk_final, SR, portfolio_final
    # return s, Assets_best, mem_weights, mem_sharpe, mem_corr, mem_ves, mem_risk, mem_n_assets, temp_list

def extract_frequent_assets(portfolios, threshold=9):
    """
    Analiza los portafolios resultantes de múltiples ejecuciones y extrae
    aquellos activos que aparecen con un peso mayor a cero en al menos 'threshold' ocasiones.

    Analyze the portfolios resulting from multiple runs and extract
    those assets that appear with a weight greater than zero on at least ‘threshold’ occasions.
    """
    asset_counts = {}

    # Recorrer cada ejecución (cada 'portfolio_final')
    for p in portfolios:
        # El DataFrame de pesos es el elemento índice 9 del retorno de SAIPO
        portfolio_df = p[9]

        # Filtrar activos con peso significativo (mayor a 0.005 para evitar ruido)
        active_assets = portfolio_df[portfolio_df['Weight'] > 0.005].index

        for asset in active_assets:
            asset_counts[asset] = asset_counts.get(asset, 0) + 1

    # Filtrar por el umbral solicitado
    frequent_assets = {asset: count for asset, count in asset_counts.items() if count >= threshold}

    # Crear un DataFrame para mejor visualización
    df_frequent = pd.DataFrame.from_dict(frequent_assets, orient='index', columns=['Frecuencia'])
    df_frequent = df_frequent.sort_values(by='Frecuencia', ascending=False)

    return df_frequent

if __name__ == "__main__":

    print("Start")

    n_experiments = 30
    sharpes = []
    rendimientos =[]
    riesgos = []
    correlaciones = []
    activos = []
    tiempos = []
    risks = []
    SRs = []
    portfolios = []

    for i in range(n_experiments):
        print("############################################")
        inicio = default_timer() # Time
        portfolios.append(SAIPO(parameters))
        fin = default_timer()
        tiempo = fin - inicio
        soluciones = portfolios[i][6]
        # print(soluciones)
        sharpes.append(round(portfolios[i][0],6))
        rendimientos.append(round(portfolios[i][1],6))
        riesgos.append(round(portfolios[i][2],6))
        correlaciones.append(round(portfolios[i][3],6))
        activos.append(portfolios[i][4])
        risks.append(round(portfolios[i][7],6))
        SRs.append(round(portfolios[i][8],6))
        portfolio_final = portfolios[i][9]
        print(portfolio_final)
        tiempos.append(round(tiempo,4))
        print(f"Ejecucion {i} finalizada")
        print(f"Tiempo de ejecucion {round(tiempo,2)}")
        print("############################################")

    summary_sharpe = pd.DataFrame(sharpes)
    summary_sharpe.columns = ["Sharpe correlation"]

    summary_returns = pd.DataFrame(rendimientos)
    summary_returns.columns = ["Expect Return"]

    summary_risks = pd.DataFrame(riesgos)
    summary_risks.columns = ["Risk correlation"]

    summary_corr = pd.DataFrame(correlaciones)
    summary_corr.columns = ["Correlation"]

    summary_n_assets = pd.DataFrame(activos)
    summary_n_assets.columns = ["Num assets"]

    summary_time = pd.DataFrame(tiempos)
    summary_time.columns = ["Time ejec"]

    summary_risks2 = pd.DataFrame(risks)
    summary_risks2.columns = ["Risk"]

    summary_SR = pd.DataFrame(SRs)
    summary_SR.columns = ["Sharpe"]

    summary = pd.concat([summary_sharpe, summary_returns, summary_risks, summary_corr, summary_SR, summary_risks2, summary_n_assets, summary_time], axis=1, sort=False)



    print(summary)
    #/content
    summary.to_csv("your_summary.csv",header=True,index=True)
    soluciones.to_csv("your_solutions.csv" ,header=True,index=True)


    """ extraer los activos que mas se repiten
    Extract the most frequently occurring assets
    """
    df_top_assets = extract_frequent_assets(portfolios, threshold=9)

    # print("\n" + "="*30)
    # print("ACTIVOS MÁS FRECUENTES (9+ apariciones)")
    # print("="*30)
    # if not df_top_assets.empty:
    #     print(df_top_assets)
    #     # Opcional: Guardar para la siguiente etapa de tu investigación
    #     df_top_assets.to_csv("C:/DOCTORADO/ART 2025/ETFS/ETF_FIB_20_26/Top_Assets_Frecuentes.csv")
    # else:
    #     print("No hay activos que cumplan con el criterio de frecuencia.3